services:
  app:
    container_name: app-tech-02
    build: .
    ports:
      - "3030:3030"
    environment:
      - MONGO_URI=mongodb://mongo:27017/techChallenge
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules 

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
